- name: configure backend server
  hosts: applicationserver
  become: yes
  tasks:
  - name: disable current nodejs
    command:
     dnf module disable nodejs -y
  - name: Enable nodejs 20
    command:
     dnf module enable nodejs:20 -y

  - name: install nodejs
    package:
     name: nodejs
     state: present
