- name: configure backend server
  hosts: applicationserver
  become: yes
  tasks:
  - name: disable current nodejs
    command:
     dnf module disable nodejs -y
  - name: Enable nodejs 20
    command:
     dnf module enable nodejs:20 -y

  - name: install nodejs
    package:
     name: nodejs
     state: present

  - name: create user   
    user:
     name: expense

  - name: create app dir
    file:
     path: /app
     state: directory

  - name: download backend code
    get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
     dest: /tmp/backend.zip

  - name: unzip backend code
    unarchive:
     src: /tmp/backend.zip
     dest: /app
     remote_src: yes