- name: Install ngnix
  hosts: backend
  become: yes
  tasks:
  - name: install ngnix
    ansible.builtin.dnf:
     name: ngnix
     state: installed
    when: ansible_os_family == "Redhat"

  - name: Install ngnix if ubuntu
    ansible.builtin.dnf:
     name: ngnix
     state: installed
    when: ansible_os_family == "Debian"
