- name: Install ngnix
  hosts: backend
  become: yes
  tasks:
  - name: install ngnix if Redhat
    ansible.builtin.dnf:
     name: ngnix
     state: installed
    when: ansible_os_family == "RedHat"

  - name: Install ngnix if ubuntu
    ansible.builtin.dnf:
     name: ngnix
     state: installed
    when: ansible_os_family == "ubuntu"
