- name: Install multiple packages
  hosts: backend
  tasks:
  - name: install packages
    ansible.builtin.package:
     name: "{{ item }}"
     state: installed
  - name: start service
    ansible.builtin.service:
     name: "{{ item }}"
     state: present
    loop:
    - gcc
    - mysql
    - git
    - zip
        