- name: install and run ngnix
  hosts: backend
  become: yes
  tasks:
  - name: install ngnix
    ansible.builtin.package:
     name: nginx
     state: present
  - name: starting ngnix
    ansible.builtin.service:
      name: nginx
      state: started   
      enabled: yes