- name: shell commands
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute ls commnd in command module
    ansible_builtin_command: ls -ltr
     register: command_result

  - name: print the output
    ansible.builtin.debug:
     msg: "{{ command_result }}"