- name: configure webserver
  hosts: webserver
  become: yes
  tasks:
  - name: install nginx
    dnf:
     name: nginx
     state: installed

  - name: enable and start ngnix
    service:
     name: nginx
     state: started
     enabled: yes